Fix compilation errors in morphing implementation
- Move env_t and morph_state_t type definitions before wavetable_sample()
- Remove duplicate type definitions
- Remove unused update_voice_tuning_if_changed() function

Fixes:
- error: unknown type name 'morph_state_t'
- error: unknown type name 'env_t'
- warning: 'update_voice_tuning_if_changed' defined but not used

rockit_engine.c:32-44: Move type definitions to top of file
rockit_engine.c:336-347: Remove duplicate definitions
rockit_engine.c:440-445: Remove unused function